### ISSUE TITLE
LogsStash confing does not handle bundled events

### ISSUE THREAD

**Issue by Dissimilis** [FantasticFiasco/serilog-sinks-http-elastic-stack#6]
LogStash config in your example:
```
http {
    codec => json
}
```
This does not work with JSON format this sink is sending (all events are treated as single message by logstash):
```
{
  "events": [
    {
        <..>
    }
  ]
}
```
 What I'm missing?

**Comment by Dissimilis** [comment]
Looks like this filter helps:
```
filter {
	    split {
                field => "events"
        }
}
```

But I noticed that DurableHttp sometimes sends events as batches and sometimes as single event JSON. This is a real headscratcher. Please consider adding information about this mixed behavior in serilog-sinks-http readme.

**Comment by Dissimilis** [comment]
Some issues with linqpad ignored "batchFormatter: new ArrayBatchFormatter()" and weird behavior happened

**Comment by FantasticFiasco** [comment]
Could you please clarify, was it only a problem with LINQPad or did you have to change anything in this repository?

You are correct regarding the json codec. The array of log events are parsed in Logstash as separate events.

> From [JSON codec plugin](https://www.elastic.co/guide/en/logstash/current/plugins-codecs-json.html):
> If the data being sent is a JSON array at its root multiple events will be created (one per element).

**Comment by Dissimilis** [comment]
I think it was problem only with LINQPad. I was not able to reproduce this issue after restarting LINQPad :)

**Comment by FantasticFiasco** [comment]
Ok, nice to hear that you got it working.

If you encounter any other problems, please let me know.
